apiVersion: v1
kind: Secret
metadata:
  namespace: airflowkex
  name: sql-alchemy-conn
data:
  sqlconstring: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3dAcG9zdGdyZXNzcWwwMTppbmZ5QDc4OTlAcG9zdGdyZXNzcWwwMS5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9haXJmbG93Cg==

