kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: airflowkex
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS



#PVC for airflowlib
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airflowkex
  name: airflow-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airflowkex
  name: airflow-dags
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi   
 


